# Generated by Django 5.2.1 on 2026-01-18 18:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCodeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_code",
                    wagtail.fields.StreamField(
                        [("code", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "label": "Public", "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                            2: ("wagtail.blocks.RawHTMLBlock", (), {"label": "Code"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("public", 0), ("title", 1), ("code", 2)]],
                                {},
                            ),
                        },
                        verbose_name="Header code",
                    ),
                ),
                (
                    "body_code",
                    wagtail.fields.StreamField(
                        [("code", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "label": "Public", "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                            2: ("wagtail.blocks.RawHTMLBlock", (), {"label": "Code"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("public", 0), ("title", 1), ("code", 2)]],
                                {},
                            ),
                        },
                        verbose_name="Body code",
                    ),
                ),
                (
                    "footer_code",
                    wagtail.fields.StreamField(
                        [("code", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "label": "Public", "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                            2: ("wagtail.blocks.RawHTMLBlock", (), {"label": "Code"}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("public", 0), ("title", 1), ("code", 2)]],
                                {},
                            ),
                        },
                        verbose_name="Footer code",
                    ),
                ),
            ],
            options={
                "verbose_name": "External code",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "navigations",
                    wagtail.fields.StreamField(
                        [("navigation", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 50},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {"label": "Links"}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("links", 4)]],
                                {
                                    "template": "core/blocks/footer_navigation_block.html"
                                },
                            ),
                        },
                        verbose_name="Navigations",
                    ),
                ),
                (
                    "navigations_en",
                    wagtail.fields.StreamField(
                        [("navigation", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 50},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {"label": "Links"}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("links", 4)]],
                                {
                                    "template": "core/blocks/footer_navigation_block.html"
                                },
                            ),
                        },
                        null=True,
                        verbose_name="Navigations",
                    ),
                ),
                (
                    "navigations_sv",
                    wagtail.fields.StreamField(
                        [("navigation", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 50},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("page", 1), ("url", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.ListBlock", (3,), {"label": "Links"}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("links", 4)]],
                                {
                                    "template": "core/blocks/footer_navigation_block.html"
                                },
                            ),
                        },
                        null=True,
                        verbose_name="Navigations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer",
                "verbose_name_plural": "Footer",
            },
        ),
        migrations.CreateModel(
            name="NotFoundPageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title displayed on the 404 Not Found page.",
                        max_length=200,
                        verbose_name="404 Page Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title displayed on the 404 Not Found page.",
                        max_length=200,
                        null=True,
                        verbose_name="404 Page Title",
                    ),
                ),
                (
                    "title_sv",
                    models.CharField(
                        help_text="Title displayed on the 404 Not Found page.",
                        max_length=200,
                        null=True,
                        verbose_name="404 Page Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description displayed on the 404 Not Found page.",
                        verbose_name="404 Page Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description displayed on the 404 Not Found page.",
                        null=True,
                        verbose_name="404 Page Description",
                    ),
                ),
                (
                    "description_sv",
                    models.TextField(
                        blank=True,
                        help_text="Description displayed on the 404 Not Found page.",
                        null=True,
                        verbose_name="404 Page Description",
                    ),
                ),
                (
                    "cards",
                    wagtail.fields.StreamField(
                        [("card", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="404 Page Cards",
                    ),
                ),
                (
                    "cards_en",
                    wagtail.fields.StreamField(
                        [("card", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="404 Page Cards",
                    ),
                ),
                (
                    "cards_sv",
                    wagtail.fields.StreamField(
                        [("card", 6)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="404 Page Cards",
                    ),
                ),
                (
                    "banner",
                    wagtail.fields.StreamField(
                        [("banner", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                        ("style", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="404 Page Banner",
                    ),
                ),
                (
                    "banner_en",
                    wagtail.fields.StreamField(
                        [("banner", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                        ("style", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="404 Page Banner",
                    ),
                ),
                (
                    "banner_sv",
                    wagtail.fields.StreamField(
                        [("banner", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            3: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("description", 1),
                                        ("image", 2),
                                        ("page", 3),
                                        ("url", 4),
                                        ("button_text", 5),
                                        ("style", 6),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                        verbose_name="404 Page Banner",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image displayed on the 404 Not Found page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="404 Page Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page 404",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RobotsTxtSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Content of the robots.txt file.",
                        verbose_name="Robots.txt content",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Robots.txt",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_networks",
                    models.TextField(
                        blank=True,
                        help_text="Enter one social network link per line.",
                        verbose_name="Social networks",
                    ),
                ),
                (
                    "default_organization_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The default image for organizations.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Default organization image",
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Flag for hero banner on home page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Flag",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="The logo of the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Site logo",
                    ),
                ),
                (
                    "logo_mobile",
                    models.ForeignKey(
                        blank=True,
                        help_text="The logo of the site for mobile devices.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Mobile logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "abstract": False,
            },
        ),
    ]
