# Generated by Django 5.2.1 on 2026-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="content_source",
            field=models.CharField(
                blank=True,
                help_text="Source of the content displayed on the site.",
                max_length=200,
                verbose_name="Content source",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="content_source_en",
            field=models.CharField(
                blank=True,
                help_text="Source of the content displayed on the site.",
                max_length=200,
                null=True,
                verbose_name="Content source",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="content_source_sv",
            field=models.CharField(
                blank=True,
                help_text="Source of the content displayed on the site.",
                max_length=200,
                null=True,
                verbose_name="Content source",
            ),
        ),
    ]
