# Generated by Django 5.2.1 on 2026-02-13 15:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_content_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_scripts",
            field=wagtail.fields.StreamField(
                [("script", 0)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.TextBlock", (), {"label": "Footer script"})
                },
                help_text="Scripts added here will be included in the footer of the site.",
                verbose_name="Footer scripts",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                blank=True,
                help_text="Text displayed in the footer of the site.",
                max_length=255,
                verbose_name="Footer text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text_en",
            field=models.CharField(
                blank=True,
                help_text="Text displayed in the footer of the site.",
                max_length=255,
                null=True,
                verbose_name="Footer text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text_sv",
            field=models.CharField(
                blank=True,
                help_text="Text displayed in the footer of the site.",
                max_length=255,
                null=True,
                verbose_name="Footer text",
            ),
        ),
    ]
