# Generated by Django 5.2.1 on 2026-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_sitesettings_footer_scripts_sitesettings_footer_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_caption",
            field=models.CharField(
                blank=True,
                help_text="Caption for the ad button displayed in the header.",
                max_length=255,
                verbose_name="Ad button caption",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_caption_en",
            field=models.CharField(
                blank=True,
                help_text="Caption for the ad button displayed in the header.",
                max_length=255,
                null=True,
                verbose_name="Ad button caption",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_caption_sv",
            field=models.CharField(
                blank=True,
                help_text="Caption for the ad button displayed in the header.",
                max_length=255,
                null=True,
                verbose_name="Ad button caption",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_text",
            field=models.CharField(
                blank=True,
                help_text="Text for the ad button displayed in the header.",
                max_length=50,
                verbose_name="Ad button text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_text_en",
            field=models.CharField(
                blank=True,
                help_text="Text for the ad button displayed in the header.",
                max_length=50,
                null=True,
                verbose_name="Ad button text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_text_sv",
            field=models.CharField(
                blank=True,
                help_text="Text for the ad button displayed in the header.",
                max_length=50,
                null=True,
                verbose_name="Ad button text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ad_button_url",
            field=models.URLField(
                blank=True,
                help_text="URL for the ad button displayed in the header.",
                verbose_name="Ad button URL",
            ),
        ),
    ]
