# Generated by Django 5.2.1 on 2026-01-18 18:16

import core.panels
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authors index page",
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="AuthorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("post", models.CharField(verbose_name="post")),
                ("post_en", models.CharField(null=True, verbose_name="post")),
                ("post_sv", models.CharField(null=True, verbose_name="post")),
                ("bio", wagtail.fields.RichTextField(blank=True)),
                ("bio_en", wagtail.fields.RichTextField(blank=True, null=True)),
                ("bio_sv", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
    ]
