# Generated by Django 5.2.1 on 2026-01-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Competitor"),
                            (1, "Basic"),
                            (2, "Standard"),
                            (3, "Premium"),
                        ],
                        default=1,
                        verbose_name="Subscription Level",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(auto_now_add=True, verbose_name="Start Date"),
                ),
                ("end_date", models.DateField(verbose_name="End Date")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is Active"),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="premium_subscription",
                        to="catalog.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Premium Subscription",
                "verbose_name_plural": "Premium Subscriptions",
                "ordering": ["end_date"],
            },
        ),
    ]
