# Generated by Django 5.2.1 on 2026-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumsubscription",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
    ]
