# Generated by Django 5.2.1 on 2026-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="pin",
            field=models.BooleanField(default=False, verbose_name="Pin comment"),
        ),
    ]
