# Generated by Django 5.2.1 on 2026-01-18 18:16

import core.panels
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        ("catalog", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overviews Category Page",
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="RatingsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overviews Index Page",
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="RatingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["h2", "bold", "italic"]},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.ListBlock", (1,), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("images", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "content_en",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["h2", "bold", "italic"]},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.ListBlock", (1,), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("images", 2)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "content_sv",
                    wagtail.fields.StreamField(
                        [("block", 3)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["h2", "bold", "italic"]},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: ("wagtail.blocks.ListBlock", (1,), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("images", 2)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                ("blockquote", models.TextField(blank=True)),
                ("blockquote_en", models.TextField(blank=True, null=True)),
                ("blockquote_sv", models.TextField(blank=True, null=True)),
                (
                    "ratings",
                    wagtail.fields.StreamField(
                        [("rating", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Rating from 1 to 10",
                                    "max_value": 10,
                                    "min_value": 1,
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("rating", 0), ("caption", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "ratings_en",
                    wagtail.fields.StreamField(
                        [("rating", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Rating from 1 to 10",
                                    "max_value": 10,
                                    "min_value": 1,
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("rating", 0), ("caption", 1)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "ratings_sv",
                    wagtail.fields.StreamField(
                        [("rating", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Rating from 1 to 10",
                                    "max_value": 10,
                                    "min_value": 1,
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("rating", 0), ("caption", 1)]],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authors.authorpage",
                    ),
                ),
                (
                    "to_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Overviews Post Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
