# Generated by Django 5.2.1 on 2026-01-18 18:16

import core.panels
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authors", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_sv",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subtitle"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_sv",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Subtitle"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("cards_section", 32),
                            ("qna", 38),
                            ("banner", 41),
                            ("html", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("core.blocks.TextBlock", (), {"label": "Text"}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("1", "1"),
                                        ("2", "2"),
                                        ("3", "3"),
                                        ("4", "4"),
                                        ("5", "5"),
                                    ],
                                    "label": "Cards in row",
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Not working for <code>Paginated organizations</code>",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Button text", "max_length": 50},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("image", 7),
                                        ("page", 8),
                                        ("button_text", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("image", 7), ("page", 8)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            13: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                    ]
                                ],
                                {},
                            ),
                            17: ("catalog.blocks.OrganizationBlock", (), {}),
                            18: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 4, "label": "Count"},
                            ),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "City", "page_type": ["catalog.City"]},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 19)]],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Organization type",
                                    "page_type": ["catalog.OrganizationType"],
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 16, "label": "Count"},
                            ),
                            24: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Parent page",
                                    "page_type": [
                                        "catalog.OrganizationType",
                                        "catalog.City",
                                    ],
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 23), ("page", 24)]],
                                {},
                            ),
                            26: ("ratings.blocks.RatingCardBlock", (), {}),
                            27: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog index page",
                                    "page_type": ["blog.BlogIndexPage"],
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 27)]],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog category page",
                                    "page_type": ["blog.BlogCategoryPage"],
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("card_style_1", 10),
                                        ("card_style_2", 11),
                                        ("card_style_3", 11),
                                        ("card_style_4", 14),
                                        ("card_style_5", 16),
                                        ("organization", 17),
                                        ("city_latest_organizations", 20),
                                        ("organization_type_latest_organizations", 22),
                                        ("paginated_organizations", 25),
                                        ("rating_card", 26),
                                        ("latest_blog_posts", 28),
                                        ("latest_blog_posts_from_category", 30),
                                    ]
                                ],
                                {"label": "Cards", "min_num": 1},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("pageurl", 2),
                                        ("button_text", 3),
                                        ("in_row", 4),
                                        ("as_carousel", 5),
                                        ("cards", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": True},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 255},
                            ),
                            35: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Answer"},
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 34), ("answer", 35)]],
                                {"icon": "help", "label": "Q&A Item"},
                            ),
                            37: (
                                "wagtail.blocks.StreamBlock",
                                [[("item", 36)]],
                                {"label": "Q&A items"},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 33), ("items", 37)]],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            40: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("description", 39),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                        ("style", 40),
                                    ]
                                ],
                                {},
                            ),
                            42: ("core.blocks.HTMLBlock", (), {}),
                        },
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_en",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("cards_section", 32),
                            ("qna", 38),
                            ("banner", 41),
                            ("html", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("core.blocks.TextBlock", (), {"label": "Text"}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("1", "1"),
                                        ("2", "2"),
                                        ("3", "3"),
                                        ("4", "4"),
                                        ("5", "5"),
                                    ],
                                    "label": "Cards in row",
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Not working for <code>Paginated organizations</code>",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Button text", "max_length": 50},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("image", 7),
                                        ("page", 8),
                                        ("button_text", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("image", 7), ("page", 8)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            13: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                    ]
                                ],
                                {},
                            ),
                            17: ("catalog.blocks.OrganizationBlock", (), {}),
                            18: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 4, "label": "Count"},
                            ),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "City", "page_type": ["catalog.City"]},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 19)]],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Organization type",
                                    "page_type": ["catalog.OrganizationType"],
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 16, "label": "Count"},
                            ),
                            24: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Parent page",
                                    "page_type": [
                                        "catalog.OrganizationType",
                                        "catalog.City",
                                    ],
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 23), ("page", 24)]],
                                {},
                            ),
                            26: ("ratings.blocks.RatingCardBlock", (), {}),
                            27: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog index page",
                                    "page_type": ["blog.BlogIndexPage"],
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 27)]],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog category page",
                                    "page_type": ["blog.BlogCategoryPage"],
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("card_style_1", 10),
                                        ("card_style_2", 11),
                                        ("card_style_3", 11),
                                        ("card_style_4", 14),
                                        ("card_style_5", 16),
                                        ("organization", 17),
                                        ("city_latest_organizations", 20),
                                        ("organization_type_latest_organizations", 22),
                                        ("paginated_organizations", 25),
                                        ("rating_card", 26),
                                        ("latest_blog_posts", 28),
                                        ("latest_blog_posts_from_category", 30),
                                    ]
                                ],
                                {"label": "Cards", "min_num": 1},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("pageurl", 2),
                                        ("button_text", 3),
                                        ("in_row", 4),
                                        ("as_carousel", 5),
                                        ("cards", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": True},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 255},
                            ),
                            35: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Answer"},
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 34), ("answer", 35)]],
                                {"icon": "help", "label": "Q&A Item"},
                            ),
                            37: (
                                "wagtail.blocks.StreamBlock",
                                [[("item", 36)]],
                                {"label": "Q&A items"},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 33), ("items", 37)]],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            40: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("description", 39),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                        ("style", 40),
                                    ]
                                ],
                                {},
                            ),
                            42: ("core.blocks.HTMLBlock", (), {}),
                        },
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_sv",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("cards_section", 32),
                            ("qna", 38),
                            ("banner", 41),
                            ("html", 42),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("core.blocks.TextBlock", (), {"label": "Text"}),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Title",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page URL", "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Button text",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("1", "1"),
                                        ("2", "2"),
                                        ("3", "3"),
                                        ("4", "4"),
                                        ("5", "5"),
                                    ],
                                    "label": "Cards in row",
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Not working for <code>Paginated organizations</code>",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255},
                            ),
                            7: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            8: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Button text", "max_length": 50},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("image", 7),
                                        ("page", 8),
                                        ("button_text", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("image", 7), ("page", 8)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description", "max_length": 255},
                            ),
                            13: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Page", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "URL", "max_length": 200, "required": False},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("description", 12),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                    ]
                                ],
                                {},
                            ),
                            17: ("catalog.blocks.OrganizationBlock", (), {}),
                            18: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 4, "label": "Count"},
                            ),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "City", "page_type": ["catalog.City"]},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 19)]],
                                {},
                            ),
                            21: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Organization type",
                                    "page_type": ["catalog.OrganizationType"],
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {"default": 16, "label": "Count"},
                            ),
                            24: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Parent page",
                                    "page_type": [
                                        "catalog.OrganizationType",
                                        "catalog.City",
                                    ],
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 23), ("page", 24)]],
                                {},
                            ),
                            26: ("ratings.blocks.RatingCardBlock", (), {}),
                            27: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog index page",
                                    "page_type": ["blog.BlogIndexPage"],
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 27)]],
                                {},
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "label": "Blog category page",
                                    "page_type": ["blog.BlogCategoryPage"],
                                },
                            ),
                            30: (
                                "wagtail.blocks.StructBlock",
                                [[("count", 18), ("page", 29)]],
                                {},
                            ),
                            31: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("card_style_1", 10),
                                        ("card_style_2", 11),
                                        ("card_style_3", 11),
                                        ("card_style_4", 14),
                                        ("card_style_5", 16),
                                        ("organization", 17),
                                        ("city_latest_organizations", 20),
                                        ("organization_type_latest_organizations", 22),
                                        ("paginated_organizations", 25),
                                        ("rating_card", 26),
                                        ("latest_blog_posts", 28),
                                        ("latest_blog_posts_from_category", 30),
                                    ]
                                ],
                                {"label": "Cards", "min_num": 1},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("pageurl", 2),
                                        ("button_text", 3),
                                        ("in_row", 4),
                                        ("as_carousel", 5),
                                        ("cards", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Title", "max_length": 255, "required": True},
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question", "max_length": 255},
                            ),
                            35: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Answer"},
                            ),
                            36: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 34), ("answer", 35)]],
                                {"icon": "help", "label": "Q&A Item"},
                            ),
                            37: (
                                "wagtail.blocks.StreamBlock",
                                [[("item", 36)]],
                                {"label": "Q&A items"},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 33), ("items", 37)]],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"label": "Description", "required": False},
                            ),
                            40: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("purple-red", "Purple-Red"),
                                        ("blue-green", "Blue-Green"),
                                        ("light-blue", "Light Blue"),
                                    ],
                                    "label": "Color",
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 1),
                                        ("description", 39),
                                        ("image", 7),
                                        ("page", 13),
                                        ("url", 15),
                                        ("button_text", 3),
                                        ("style", 40),
                                    ]
                                ],
                                {},
                            ),
                            42: ("core.blocks.HTMLBlock", (), {}),
                        },
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authors.authorpage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="blog.blogpostpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="blog.BlogTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
