# Generated by Django 5.2.1 on 2026-01-19 15:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="description",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="description_sv",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
    ]
