# Generated by Django 5.2.1 on 2026-01-25 11:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_organization_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="qna",
            field=wagtail.fields.StreamField(
                [("qna_block", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Question", "max_length": 255},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"label": "Answer"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 1), ("answer", 2)]],
                        {"icon": "help", "label": "Q&A Item"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("item", 3)]],
                        {"label": "Q&A items"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 4)]],
                        {},
                    ),
                },
                verbose_name="Q&A",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="qna_en",
            field=wagtail.fields.StreamField(
                [("qna_block", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Question", "max_length": 255},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"label": "Answer"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 1), ("answer", 2)]],
                        {"icon": "help", "label": "Q&A Item"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("item", 3)]],
                        {"label": "Q&A items"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 4)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Q&A",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="qna_sv",
            field=wagtail.fields.StreamField(
                [("qna_block", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Question", "max_length": 255},
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"label": "Answer"}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 1), ("answer", 2)]],
                        {"icon": "help", "label": "Q&A Item"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("item", 3)]],
                        {"label": "Q&A items"},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("items", 4)]],
                        {},
                    ),
                },
                null=True,
                verbose_name="Q&A",
            ),
        ),
    ]
