# Generated by Django 5.2.1 on 2026-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_organization_qna_organization_qna_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="avg_rating_weight",
            field=models.SmallIntegerField(
                default=100,
                help_text="From 115 to 0",
                verbose_name="Average Rating Weight",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="rating_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
